packages:
  - 'apps/*'
  - 'packages/*'
nodeLinker: hoisted

catalog:
  # React
  react: ^19
  react-dom: ^19
  '@types/react': ^19
  '@types/react-dom': ^19

  # TypeScript
  typescript: ^6.0.2
  '@types/node': ^25.6.0

  # Build
  vite: ^8.0.8
  '@vitejs/plugin-react': ^6.0.1

  # Test
  vitest: ^4.1.4
  vite-tsconfig-paths: ^6.1.1
  '@playwright/test': ^1.59.1
  msw: ^2.13.2

  # Lint & Format
  eslint: ^10.2.0
  prettier: ^3.8.2
  eslint-plugin-prettier: ^5.5.5

  # Framework
  next: ^16.2.3
  '@next/eslint-plugin-next': ^16.2.3
